salesforce.settings:
  type: config_object
  label: 'Salesforce Settings'
  mapping:
    global_push_limit:
      type: integer
      label: 'Salesforce push queue global limit'
    pull_max_queue_size:
      type: integer
      label: 'Salesforce pull queue max size'
    standalone:
      type: boolean
      label: 'Provide standalone push queue processing endpoint.'
    show_all_objects:
      type: boolean
      label: 'Show all Salesforce objects in mapping UI, including system and non-writeable tables'
    use_latest:
      type: boolean
      label: 'Use latest REST API Version by default'
    rest_api_version:
      type: mapping
      label: 'REST API Version'
      mapping:
        label:
          type: string
          label: 'Label'
        url:
          type: string
          label: 'URL'
        version:
          type: string
          label: 'Version'
