salesforce.auth_provider_settings.oauth_encrypt:
  type: mapping
  label: 'Salesforce JWT Provider Settings'
  mapping:
    consumer_key:
      type: string
      label: 'Consumer Key'
    consumer_secret:
      type: string
      label: 'Consumer Secret'
    login_url:
      type: uri
      label: 'Login URL'
    encryption_profile:
      type: encrypt.profile.[%key]
      label: 'Encryption Profile ID'
