salesforce.auth_provider_settings.jwt:
  type: mapping
  label: 'Salesforce JWT Provider Settings'
  mapping:
    consumer_key:
      type: string
      label: 'Consumer Key'
    login_user:
      type: string
      label: 'Login User'
    login_url:
      type: uri
      label: 'Login URL'
    encrypt_key:
      type: key.key.[%key]
      label: 'Encryption Key ID'

